config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :new, :create] do
    resources :comments, only: [:index, :show, :create, :destroy]
  end
  resources :session, only: [:new, :create, :destroy]
  resources :goals do
    resources :comments, only: [:index, :show, :create, :destroy]
  end
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

  def correct_redirect
    self.commentable_type == "Goal" ? "goal_url(self.id)" : "user_url(self.id)"
  end
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  include Commentable
  validates :title, :user_id, presence: true

  belongs_to :user,
             foreign_key: :user_id,
             class_name: "User"
end

app/models/goal_comment.rb
class GoalComment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Commentable
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true

  has_many :goals, dependent: :destroy,
                   foreign_key: :user_id,
                   class_name: "Goal"

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/models/user_comment.rb
class UserComment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: self.session[:session_token])
    @current_user
  end

  def login_user!(user)
    self.session[:session_token] = user.reset_session_token!
    current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def redirect_if_logged_out
    redirect_to new_session_url unless logged_in?
  end

  def comment_type
    @comments = params[:user_id] == nil ? Comment.all.where({ commentable_type: "Goal", commentable_id: params[:goal_id] }) : Comment.all.where({ commentable_type: "User", commentable_id: params[:user_id] })
    @comments
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = comment_type
    render :index
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    redirect = params[:user_id] == nil
    if @comment.save
      flash[:notice] = ["Comment saved"]
      if redirect
        redirect_to goal_url(@comment.commentable_id)
      else
        redirect_to user_url(@comment.commentable_id)
      end
    else
      flash[:error] = ["Unable to add comment"]
      redirect_to users_url
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type, :author_id)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :redirect_if_logged_out

  def index
    @goals = current_user.goals
    render :index
  end

  def show
    @goal = Goal.find(params[:id])
    @comments = @goal.comments
    if @goal["public"] == true || @goal.user_id == current_user.id
      render :show
    else
      flash[:errors] = ["This goal is marked private"]
      redirect_to goals_url
    end
  end

  def new
    @goal = Goal.new()
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      flash[:notice] = ["Goal successfully created"]
      redirect_to goal_url(@goal)
    else
      flash[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.user_id == current_user.id
      @goal.update(completed: !@goal.completed)
      redirect_to goals_url
    else
      flash[:errors] = ["You can't complete other users goals"]
      redirect_back
    end
  end

  def destroy
    @goal = Goal.find(params[:id])

    if @goal.user_id == current_user.id
      @goal.destroy
      redirect_to goals_url
    else
      flash[:errors] = ["You can't delete other users goals"]
      redirect_to goals_url
    end
  end

  private

  def goal_params
    params[:goal][:public] = params[:goal][:public] == "private" ? false : true
    params[:goal][:completed] = params[:goal][:completed] == "complete" ? true : false
    params.require(:goal).permit(:title, :details, :public, :completed)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user.nil?
      flash.now[:errors] = ["Username or password incorrect"]
      render :new
    else
      login_user!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    current_user.reset_session_token! && session[:session_token] = nil
    redirect_to users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    @goals = @user.goals
    @comments = Comment.where(commentable_type: "User", commentable_id: @user.id)
    render :show
  end

  def new
    @user = User.new()
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=hidden name=authenticity_token value=#{h(form_authenticity_token)}>".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.html.erb
<% type_url = comment_type == :user ? user_comments_url(user_id) : goal_comments_url(goal_id) %>
<form action="<%= type_url %>" method="post">
<%= auth_token %>
<input type="hidden" name="comment[commentable_type]" value="<%= commentable_type %>">
<input type="hidden" name="comment[commentable_id]" value="<%= commentable_id %>">
<label for="comment_field">Comment
  <textarea name="comment[body]" id="comment_field"></textarea>
</label>

<input type="submit" value="Add Comment">
</form>

app/views/comments/index.html.erb
<h1>Comments</h1>

<ul>
  <% @comments.each do |comment| %>
    <p><%= comment.body %></p>
  <% end %>
</ul>

app/views/goals/index.html.erb
<div class="index_goals">
<h2>Your Goals</h2>

<%= link_to("Add a new goal", new_goal_url) %>
<ul>
  <% @goals.each do |goal| %>
    <li><%= link_to(goal.title, goal_url(goal)) %></li>
    <p><%= goal.public ? 'public' : 'private' %></p>
    <p><%= goal.completed ? 'Complete' : 'Not Completed' %></p>
    <br>
    <%= button_to(goal.completed ? "Mark as incomplete" : "Mark as complete", goal_url(goal), method: :patch) %>
    <br>
    <%= button_to('Delete this goal', goal_url(goal), method: :delete) %>
  <% end %>
</ul>
</div>

app/views/goals/new.html.erb
<h3>Add a new goal</h3>
<form action="<%= goals_url %>" method="post">
<%= auth_token %>
  <label for="title_field">Title
    <input type="text" name="goal[title]" id="title_field" value="<%= @goal.title %>">
  </label>
  <label for="details_field">Details
    <textarea name="goal[details]" id="details_field" cols="30" rows="10"><%= @goal.details %></textarea>
  </label>
  <label for="public_field">Private?
    <input type="checkbox" name="goal[public]" id="public_field" value="private" <%= 'checked' if @goal.public == false %>>
  </label>
  <label for="completed_field">Completed?
    <input type="checkbox" name="goal[completed]" id="completed_field" value="complete" <%= 'checked' if @goal.completed == true %>>
  </label>

  <input class="submit" type="submit" value="Add Goal">
</form>

app/views/goals/show.html.erb
<div class="show_goal">

  <h3>Goal:</h3>

  <ul>
    <li><h4>Title</h4><%= @goal.title %></li>
    <li><h4>Details</h4><%= @goal.details %></li>
    <li><h4>Visibility</h4><%= @goal["public"] == true ? "Public" : "Private" %></li>
    <li><h4>Status</h4><%= @goal.completed == true ? "Completed" : "Not Completed" %></li>
  </ul>
    <br>
    <% if current_user.id == @goal.user_id %>
      <%= button_to(@goal.completed ? "Mark as incomplete" : "Mark as complete", goal_url(@goal), method: :patch) %>
    <br>
    <%= button_to('Delete this goal', goal_url(@goal), method: :delete) %>
    <% end %>
  <br>
    <div class="goal_comments">
    <h3>Comments:</h3>
      <ul>
        <% @comments.each do |comment| %>
          <li><%= comment.body %></li>
        <% end %>
      </ul>
    <h3>Add a comment</h3>
    <div>
      <%= render "comments/comment_form", comment_type: :goal, goal_id: @goal.id, commentable_type: "Goal", commentable_id: @goal.id %>
    </div>
    </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AaGreatGoals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 style="text-align: center;">Goaling App</h1>
    <div style="color: red;">
      <% flash[:errors].to_a.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
    <div style="color: green;">
    <% if flash[:notice] != nil %>
      <% flash[:notice].each do |notice| %>
        <p><%= notice %></p>
      <% end %>
    <% end %>
    </div>
   
    <% if current_user.nil? %>
      <p><%= link_to("Login", new_session_url) %></p>
      <p>or</p>
      <p><%= link_to("Sign Up", new_user_url) %></p>
    <% else %>
      <p><%= link_to("Logout", session_url(current_user.id), method: :delete) %></p>
    <% end %>
    <% if logged_in? %>
      <%= button_to("Create Goal", new_goal_url, method: :get) %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/session/new.html.erb
<h1>Login</h1>

<%= render 'shared/login_form', user: @user, method: :login %>

app/views/shared/_login_form.html.erb
<% action_url = method == :login ? session_index_url : users_url %>
<% submit_text = method == :login ? "Login" : "Create Account" %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <label for="username_field">Username
    <input type="text" name="user[username]" id="username_field">
  </label>
  
  <label for="password_field">Password
    <input type="password" name="user[password]" id="password_field">
  </label>

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
  <%= link_to(user.username.to_s, user_url(user)) %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'shared/login_form', user: @user, method: :signup %>

app/views/users/show.html.erb
<h2><%= @user.username %>'s Profile</h2>

<div class="profile_user_comments">
<h3>Comments:</h3>
  <ul>
      <% @comments.each do |comment| %>
        <li><%= comment.body %></li>
      <% end %>
    </ul>
    <h3>Add a comment</h3>
    <div>
      <%= render "comments/comment_form", comment_type: :user, user_id: @user.id, commentable_type: "User", commentable_id: @user.id %>
    </div>
</div>

<div class="profile_goals">
<h3><%= @user.username %>'s Goals</h3>
  <ul>
    <% @goals.each do |goal| %>
      <% if goal.public || goal.user_id == current_user.id %>
        <li><%= link_to(goal.title, goal_url(goal)) %></li> 
      <% end %>
      <% if goal.user_id == current_user.id %>
        <%= button_to(goal.completed == true ? "Mark as incomplete" : "Mark as complete", goal_url(goal), method: :patch) %>
      <% end %>
    <% end %>
  </ul>
</div>
<%= link_to("All Users", root_url) %>
<br>
<%= link_to("Create Goal", new_goal_url) %>